export default {
  
    "login": "DarkWorldCoder",
    "id": 63191911,
    "node_id": "MDQ6VXNlcjYzMTkxOTEx",
    "avatar_url": "https://avatars0.githubusercontent.com/u/63191911?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/DarkWorldCoder",
    "html_url": "https://github.com/DarkWorldCoder",
    "followers_url": "https://api.github.com/users/DarkWorldCoder/followers",
    "following_url": "https://api.github.com/users/DarkWorldCoder/following{/other_user}",
    "gists_url": "https://api.github.com/users/DarkWorldCoder/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/DarkWorldCoder/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/DarkWorldCoder/subscriptions",
    "organizations_url": "https://api.github.com/users/DarkWorldCoder/orgs",
    "repos_url": "https://api.github.com/users/DarkWorldCoder/repos",
    "events_url": "https://api.github.com/users/DarkWorldCoder/events{/privacy}",
    "received_events_url": "https://api.github.com/users/DarkWorldCoder/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Ayush Niroula",
    "company": "None",
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 3,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2020-04-05T11:59:50Z",
    "updated_at": "2020-10-11T12:23:41Z"
  
};
